export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS";
export const ACCOUNT_LIST_FAIL = "ACCOUNT_LIST_FAIL";

export const ACCOUNT_ADD_SUCCESS = "ACCOUNT_ADD_SUCCESS";
export const SET_ACTIVE_ACCOUNT = "SET_ACTIVE_ACCOUNT";
