export const ENTRY_LIST_REQUEST = "ENTRY_LIST_REQUEST";
export const ENTRY_LIST_SUCCESS = "ENTRY_LIST_SUCCESS";
export const ENTRY_LIST_FAIL = "ENTRY_LIST_FAIL";

export const ENTRY_CREATE_SUCCESS = "ENTRY_CREATE_SUCCESS";
export const ENTRY_DELETE_SUCCESS = "ENTRY_DELETE_SUCCESS";
